version: 2.1
jobs:
  run-test:
    docker:
      - image: mcr.microsoft.com/playwright:v1.46.0-jammy
    steps:
      - checkout
      - run:
          name: Download dependency
          environment:
            SECRET_KEY: SECRET_KEY
          command: npm ci
      - run:
          name: Install Playwright Browsers
          command: |
            npx playwright install chrome
            npx playwright install msedge
      - run:
          name: Run tests
          command: npm run test
      - store_test_results:
          path: report.json
      - store_artifacts:
          path: report.json
      # - run:
      #     name: Install AWS CLI
      #     command: |
      #       apt-get update
      #       apt-get install -y awscli
      # - run:
      #     name: Upload report.json to S3
      #     command: |
      #       aws s3 cp report.json s3://mycircleci/report.json
      - aws-cli/install
      - aws-cli/s3 cp:
          arguments: report.json s3://mycircleci/report.json

workflows:
  run-test-workflow:
    jobs:
      - run-test
