version: 2.1
jobs:
  run-test:
    docker:
      - image: mcr.microsoft.com/playwright:v1.46.0-jammy
    steps:
      - checkout
      - run:
          name: Download dependency
          environment:
            SECRET_KEY: SECRET_KEY 
          command: npm ci
      - run:
          name: Install Playwright Browsers
          command: |
            npx playwright install chrome
            npx playwright install msedge
      - run:
          name: Install Elasticsearch Client
          command: npm install @elastic/elasticsearch
      - run:
          name: Run tests
          command: npm run test
      - store_test_results:
          path: report.json
      - store_artifacts:
          path: report.json
      - run:
          name: Test Internet Connectivity
          command: curl -I https://www.google.com
      - run:
          name: Check Elasticsearch connectivity
          command: |
            curl -X GET "https://192.168.100.20:9200/_cluster/health?pretty" -u elastic:your_password -k
      - run:
          name: Send Results to Elasticsearch
          command: node sendResults.js

workflows:
  run-test-workflow:
    jobs:
      - run-test
